// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');

const config = {
  title: 'Betty Cracker Recipes', //site title
  tagline: 'Recipes for Breakfast, Lunch, Dinner, & Dessert', //tagline on homepage
  url: 'https:/betty-cracker-recipes.github.io',
  baseUrl: '/BC-Recipes/',
  trailingSlash: true,
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico', // tab image
  organizationName: 'betty-cracker-recipes', //  GitHub org/user name.
  projectName: 'BC-Recipes', //Reepo name.
  
  
  presets: [
    [
      'classic',
      ({
        docs: {sidebarPath: require.resolve('./sidebars.js'), editUrl: 'https://github.com/betty-cracker-recipes/BC-Recipes'}, // links side bar to docs (aka recipes) tab
        blog: {showReadingTime: true, editUrl: 'https://github.com/betty-cracker-recipes/BC-Recipes'},  
        theme: {customCss: require.resolve('./src/css/custom.css')}, // applies custom css to entire site
      }),
    ],
  ],

  themeConfig:
    (
      {
      navbar: {
        title: 'Home', // Home Tab Label
        logo: {alt: 'My Site Logo', src: 'img/chef-2.png'}, // Home Tab Icon
        // NAV BAR ITEMS
        items: [
          // Recipes Tab
          {type: 'doc', docId: 'intro', position: 'left', label: 'Recipes'},
          // Gallery Tab
          {to: '/gallery', label: 'Gallery', position: 'left'},
          // Blog Tab
          {to: '/blog', label: 'Blog', position: 'left'},
          //Git Repo
          {href: 'https://github.com/betty-cracker-recipes/BC-Recipes', label: 'GitHub', position: 'right'},
        ],
      },
      // SEARCH BAR - NAV BAR
      algolia: {
          apiKey:'095d0154d0a88751c86fdf134f5f5775', // search only api key, different from one used in .env
          indexName:'bc', // created new index and named in algolia
          appId:'33MRM77352', //automatically generated by algolia
      },

      // FOOTER ITEMS
      footer: {
        style: 'dark',
        links: [
       
          {
            title: 'Documentation',
            items: [
              {label: 'GitHub', href: 'https://github.com/betty-cracker-recipes/BC-Recipes'},
            ],
          },
          {
            title: 'Contact Us',
            items: [
             
              {
                label: 'Email',
                href: 'https://github.com/betty-cracker-recipes/BC-Recipes',
              },
            ],
          },
          {
            title: 'Documentation',
            items: [
             
              {
                label: 'GitHub',
                href: 'https://github.com/betty-cracker-recipes/BC-Recipes',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Betty Cracker Recipes.`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
};

module.exports = config;
